import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Formik, Form, Field } from 'formik'
import { FaSave } from 'react-icons/fa'

const ContainerInfo = () => {
    const [loading, setLoading] = useState(true)
    const [container, setContainer] = useState({})
    const {id} = useParams()

    useEffect(() => {
        //pretend to fetch containerInfo
        //create pretend data
        setTimeout(() => {
            setContainer({
                ID: id,
                adresa: "Bana Jelacica 55",
                ocjena: 3.4,
                img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dumpster-non.JPG/220px-Dumpster-non.JPG",
                komentari: [
                    {
                        id: 1,
                        autor: "user",
                        komentar: "nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches nice job bitches ",
                        time: "12.04.2019 17:15"
                    },
                    {
                        id: 2,
                        autor: "user1",
                        komentar: "nice job 'bitches'",
                        time: "12.04.2019 17:15"
                    },
                    {
                        id: 3,
                        autor: "user2",
                        komentar: "nice 'job' bitches",
                        time: "12.04.2019 17:15"
                    },
                    {
                        id: 4,
                        autor: "user3",
                        komentar: "'nice' job bitches",
                        time: "12.04.2019 17:15"
                    }
                ]
            })
            setLoading(false)
        }, 2000)
    },[])

    if(loading) return <div>loading...</div>

    return (
        <Formik
            initialValues={{
                ID: container.ID,
                adresa: container.adresa,
                ocjena: container.ocjena,
                userOcjena: null,
                img: container.img}}
            onSubmit={(value) => console.log(value)}
        >
                <Form>
                    <div style={{display: 'flex', flexFlow: 'row wrap', 
                    margin:'10px', marginTop:'0px'}}>
                        <img src={container.img}
                            style={{height:'200px', width:'200px', marginRight:'10px'}}/>
                        <div style={{margin:'10px', marginLeft:'0px'}}>
                            <div style={{display: 'flex', flexDirection: 'row', 
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>ID</label>
                                </div>
                                <Field name='ID' disabled type="text" placeholer='Autogenerated'
                                    style={{width:'100%'}}
                                />
                            </div>
                            <div style={{display: 'flex', flexDirection: 'row', 
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>Adresa</label>
                                </div>
                                <Field name='adresa' disabled type="text" placeholer='Petrova 13, Zagreb...'
                                    style={{width:'100%'}}
                                />
                            </div>
                            <div style={{display: 'flex', flexDirection: 'row', 
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>Ocjena</label>
                                </div>
                                <Field name='ocjena' disabled type="text" placeholer='5.0'
                                    style={{width:'100%'}}
                                />
                            </div>
                            <div style={{display: 'flex', flexDirection: 'row', 
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>Vaša Ocjena</label>
                                </div>
                                <Field name='userOcjena' type="text" placeholer='5.0'
                                    style={{width:'100%'}}
                                />
                            </div>
                            <div style={{display:'flex', flexDirection:'row', justifyContent:'space-evenly'}}>
                                <button type="submit" style={{outline: 0,border: 0,background: 'none'}}>
                                    <FaSave style={{backgroundColor:'white', borderRadius:'8px', height:'24px', width:'24px', borderRadius:'8px'}} />
                                </button>
                            </div>
                        </div>
                        <div style={{backgroundColor:'darkgrey', width:'100%'}}>
                            <label style={{margin:'0.5rem'}}>Komentari</label>
                        </div>
                        <div style={{border: '1px solid grey', borderTop: 'none', width:'100%'}}>
                            {
                                container.komentari.map((value) => 
                                    <div key={value.id} style={{display:'flex', flexDirection:'column', 
                                            borderBottom:'1px solid grey', width: '100%'}}>
                                        <div style={{backgroundColor:'lightgrey', width:'100%', textAlign: 'left'}}>
                                            <span style={{margin:'0.5rem', width:'100%'}}>
                                                {value.autor}
                                            </span>
                                        </div>
                                        <div style={{marginLeft:'1rem', overflow:'hidden', textAlign: 'left'}}>
                                            <span style={{tetAlign:'left'}}>
                                                {value.komentar}
                                            </span>
                                        </div>
                                    </div>
                                )
                            }
                        </div>
                    </div>
                </Form>
        </Formik>
    )
}

export default ContainerInfo