import React, {useCallback, useEffect, useState} from 'react'
import { useParams } from 'react-router-dom'
import { Formik, Form, Field } from 'formik'
import { FaSave } from 'react-icons/fa'
import axios from "axios";
import {AuthStore} from "../../store/AuthStore";

const ContainerInfo = () => {
    const [loading, setLoading] = useState(true)
    const [container, setContainer] = useState({ID: 0, adresa: '', ocjena: -1, img: '', komentari: []})
    const {id} = useParams()

    useEffect(() => {
        axios('/waste-containers/' + id, {
            method: 'GET'
        }).then((res) => {
            if (res.status === 200) {
                setContainer({
                    ID: res.data.id,
                    adresa: res.data.address,
                    ocjena: 3.4,
                    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dumpster-non.JPG/220px-Dumpster-non.JPG",
                    komentari: []
                })
                setLoading(false)

                loadComments()
            }
        })
    },[])

    function loadComments() {
        axios.get('/reviews/for-waste-container/' + id)
        .then((res) => {
            if (res.status === 200) {
                const komentari = res.data.map((rev) => ({
                    id: rev.id,
                    autor: rev.author,
                    komentar: rev.comment,
                    vrijeme: new Date(rev.postedAt).toLocaleDateString()
                }))

                setContainer(prevState => {
                    let copy = Object.assign({}, prevState)

                    copy.komentari = komentari

                    return copy
                })
            }
        })
    }

    if(loading) return <div>loading...</div>

    return (
        <Formik
            initialValues={{
                ID: container.ID,
                adresa: container.adresa,
                ocjena: container.ocjena,
                userOcjena: null,
                img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Dumpster-non.JPG/220px-Dumpster-non.JPG"}}
            onSubmit={(value) => {
                axios('/reviews/for-waste-container/' + id + '/create', {
                    method: 'POST',
                    data: {
                        grade: value.userOcjena,
                        comment: value.userKomentar
                    }
                }).then((res) => {
                    if (res.status === 200) {
                        loadComments()
                    }
                })
            }}
        >
                <Form>
                    <div style={{display: 'flex', flexFlow: 'row wrap', 
                    margin:'10px', marginTop:'0px'}}>
                        <img src={container.img}
                            style={{height:'200px', width:'200px', marginRight:'10px'}}/>
                        <div style={{margin:'10px', marginLeft:'0px'}}>
                            <div style={{display: 'flex', flexDirection: 'row', 
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>ID</label>
                                </div>
                                <Field name='ID' disabled type="text" placeholer='Autogenerated'
                                    style={{width:'100%'}}
                                />
                            </div>
                            <div style={{display: 'flex', flexDirection: 'row', 
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>Adresa</label>
                                </div>
                                <Field name='adresa' disabled type="text" placeholer='Petrova 13, Zagreb...'
                                    style={{width:'100%'}}
                                />
                            </div>
                            <div style={{display: 'flex', flexDirection: 'row', 
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>Ocjena</label>
                                </div>
                                <Field name='ocjena' disabled type="text" placeholer='5.0'
                                    style={{width:'100%'}}
                                />
                            </div>
                            <div style={{display: 'flex', flexDirection: 'row', 
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>Vaša Ocjena</label>
                                </div>
                                <Field name='userOcjena' type="number" placeholer='5.0'
                                    style={{width:'100%'}} required='true'
                                />
                            </div>
                            <div style={{display: 'flex', flexDirection: 'row',
                                marginBottom:'10px', width:'260px'}}>
                                <div style={{backgroundColor:'darkgrey'}}>
                                    <label style={{margin:'0.5rem'}}>Vaš Komentar</label>
                                </div>
                                <Field name='userKomentar' type="text" placeholer='Komentar'
                                       style={{width:'100%'}} required='true'
                                />
                            </div>
                            <div style={{display:'flex', flexDirection:'row', justifyContent:'space-evenly'}}>
                                <button type="submit" style={{outline: 0,border: 0,background: 'none'}}>
                                    <FaSave style={{backgroundColor:'white', borderRadius:'8px', height:'24px', width:'24px', borderRadius:'8px'}} />
                                </button>
                            </div>
                        </div>
                        <div style={{backgroundColor:'darkgrey', width:'100%'}}>
                            <label style={{margin:'0.5rem'}}>Komentari</label>
                        </div>
                        <div style={{border: '1px solid grey', borderTop: 'none', width:'100%'}}>
                            {
                                container.komentari.map((value) => 
                                    <div key={value.id} style={{display:'flex', flexDirection:'column', 
                                            borderBottom:'1px solid grey', width: '100%'}}>
                                        <div style={{backgroundColor:'lightgrey', width:'100%', textAlign: 'left'}}>
                                            <span style={{padding:'0.5rem', width:'50%', float: 'left'}}>
                                                {value.autor}
                                            </span>
                                            <span style={{padding:'0.5rem', width:'50%', float: 'right', textAlign: 'right'}}>
                                                {value.vrijeme}
                                            </span>
                                        </div>
                                        <div style={{marginLeft:'1rem', overflow:'hidden', textAlign: 'left', clear: 'both'}}>
                                            <span style={{tetAlign:'left'}}>
                                                {value.komentar}
                                            </span>
                                        </div>
                                    </div>
                                )
                            }
                        </div>
                    </div>
                </Form>
        </Formik>
    )
}

export default ContainerInfo