compile_pdf:
  image: tianon/latex
  script:
    - cd dokumentacija
    - latexmk -pdf OPP_2019_BashCrash.tex
    - cp OPP_2019_BashCrash.pdf ..
  artifacts:
    paths:
      - OPP_2019_BashCrash.pdf
 
