compile_pdf:
  image: tianon/latex
  script:
    - cd dokumentacija
    - latexmk -pdf OPP_ProjektnaDokumentacija_v5.tex
  artifacts:
    paths:
      - dokumentacija/OPP_ProjektnaDokumentacija_v5.pdf
 
